### ISSUE TITLE
Uncaught ReferenceError: err is not defined

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/level-exists#7]
```
     Uncaught ReferenceError: err is not defined
      at ReadStream.<anonymous> (node_modules/level-exists/index.js:38:8)
      at ReadStream._cleanup (node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:75:10)
      at Object.cb (node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:53:19)
      at Multilevel._clearRequests (node_modules/multileveldown/leveldown.js:122:35)
      at node_modules/multileveldown/leveldown.js:104:10
      at f (node_modules/once/once.js:17:25)
      at onclose (node_modules/multileveldown/node_modules/end-of-stream/index.js:43:45)
      at Encoder.destroy (node_modules/pbs/encoder.js:24:10)
      at Duplexify._destroy (node_modules/duplexify/index.js:187:66)
      at node_modules/duplexify/index.js:174:10
```

Look at https://github.com/juliangruber/level-exists/blob/master/index.js#L37, the bug is pretty obvious ...

**Comment by juliangruber** [comment]
could you submit a pull request for this?

**Comment by binarykitchen** [comment]
Done, see above link. Tested on my machine on different node/npm versions. Works fine. 

@juliangruber Hope you can merge, bump package version and npm publish that soon?

**Comment by binarykitchen** [comment]
thanks - good work, especially that new unit test case

still, i recommend to pinpoint versions instead because there isn't always a guarantee that minor version bumps come without breaking changes.
